name: Go

on:
  push:
    tags:
      - 'stable'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Docker
      uses: docker/build-push-action@v1
      with:
        username: pinpointbot
        password: ${{ secrets.PP_GITHUB_TOKEN }}
        repository: pinpt/agent.next/agent.next
        dockerfile: build/Dockerfile
        registry: docker.pkg.github.com
        tags: stable
